### ISSUE TITLE
Problem in ct models in model.py

### ISSUE THREAD

**Issue by alitair** [nianlonggu/WhisperSeg#1]
`segmenter = WhisperSegmenterFast( "nccratliri/whisperseg-canary-ct2", device="cuda" )`

is currently throwing an error here:

```
audio, _ = librosa.load( "data/example_subset/Canary/test/llb16_0602_2018_05_07_14_23_49.wav",
                         sr = sr )
print(audio.shape)
prediction = segmenter.segment(  audio, sr = sr, min_frequency = min_frequency, spec_time_step = spec_time_step,
                       min_segment_length = min_segment_length, eps = eps,num_trials = num_trials )
```

in this block in model.py : 

  ```
          """ 
            This is the code if model is the converted ctranslate model
            """
            sliced_audios_features_batch = sliced_audios_features[pos:pos+batch_size]
            actual_batch_size = len(sliced_audios_features_batch)
            features = ctranslate2.StorageView.from_array(np.asarray([ item[2] for item in sliced_audios_features_batch ]))
            prompt = tokenizer.convert_tokens_to_ids(
                [ "<|startoftranscript|>", "<|en|>", "<|notimestamps|>"]
            )
            ## the ctranslate converted model typically requires a larger max length than the one required by the original huggingface model, so we set max_length to a large value.
            ## Note Ctranslate Whisper does not support top_p samplin
            model_output = model.generate(features, [ prompt for _ in range(actual_batch_size) ], 
                                                 max_length = max_length, beam_size = num_beams,
                                                 sampling_topk = top_k,
                                                 length_penalty = length_penalty
                                              )
```

I'll try to get the stack trace later, but I think it is due to code uploaded in the last few days. I downloaded a few days ago and it runs fine on my laptop; downloaded today it fails in colab (under cpu or cuda)

**Comment by alitair** [comment]
`segmenter = WhisperSegmenter( "nccratliri/whisperseg-canary", device="cuda" )`

works fine (e.g. the non-ct2 version)

**Comment by nianlonggu** [comment]
Hi, I just tried the google colab notebook: https://colab.research.google.com/gist/nianlonggu/188146334ef360208d374ff2821ccf76/copy-of-whisperseg-canary-test.ipynb   and did not encounter errors. 
Can you reclone the repo and install a new anaconda environment and try again? If the error still happens, you can change the line to "segmenter = WhisperSegmenterFast( "nccratliri/whisperseg-canary-ct2", device="cpu" )"  (change cuda to cpu) and share the error message you get.

**Comment by nianlonggu** [comment]
If on your laptop you see the error like below:
```
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)
```
it is because of the issue of cudnn version mismatch. Then in the anaconda environment, run "conda install conda-forge::cudnn==8.9.7.29 -y" will fix the issue. I have updated the installation description in README.

**Comment by alitair** [comment]
It all runs fine on device=cpu.

**Comment by nianlonggu** [comment]
it is mostly like the cudnn issue. see my comment above.
